services:
  db:
    image: mysql
    restart: always
    ports:
      - '3000:5000'
    environment:
      MYSQL_DATABASE: tp_ids
      MYSQL_ROOT_PASSWORD: codigofiuba
    volumes:
      - ../sql/init.sql:/docker-entrypoint-initdb.d/init.sql